version: "3.9"
services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    env_file:
      - dev.env
    ports:
      - "5433:5433"
    command:
      - "postgres"
      - "-c"
      - "port=5433"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
    - app-network

  backend:
    build:
      dockerfile: java-dockerfile
    container_name: java-backend
    depends_on:
      - postgres
      - mailhog
    env_file:
      - dev.env
    ports:
      - "8081:8081"
    networks:
      - app-network

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

volumes:
  db-data:
networks:
  app-network:
