package com.school.exception;

public enum ExceptionLocations {
    USER_SERVICE_NOT_FOUND,
    USER_SERVICE_VALIDATION,
    USER_DTO_ENTITY_VALIDATION,
    ORDER_DTO_ENTITY_VALIDATION,
    ORDER_SERVICE_VALIDATION,
    ORDER_SERVICE_NOT_FOUND,
    ATTACHMENT_NOT_FOUND,
    TOKEN_SERVICE_VALIDATION,
    TOKEN_SERVICE_CONFLICT,
    TOKEN_NOT_FOUND,
    TOKEN_FORBIDDEN,
    RESOURCE_NOT_FOUND,
    MAIL_ERROR,
    CONTROLLER_VALODATION_ERROR,
    KEY_ERROR;
}
